title: Keine Keine
author: A. v. L.
email: a-v-l@gmx.de
description: > # this means to ignore newlines until "baseurl:"
  In zwei Sekunden 50% weniger Altpapier

# social links
github_username:  a-v-l # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
